import funkin.states.PlayState;
import funkin.data.Stats;
import funkin.data.Highscore;
import funkin.data.JudgmentManager.JudgmentData;
import funkin.game.notes.*;
import funkin.game.playfields.*;
import funkin.game.hud.*;
import funkin.game.huds.BaseHUD;
import funkin.objects.Character;